package com.hongjun.model;

import jakarta.annotation.Generated;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   文章管理
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blog_article
 */
public class BlogArticleDO implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.123782+08:00", comments="Source field: blog_article.id")
    private Integer id;

    /**
     * Database Column Remarks:
     *   标签ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.tag_id")
    private Integer tagId;

    /**
     * Database Column Remarks:
     *   文章标题
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.title")
    private String title;

    /**
     * Database Column Remarks:
     *   简述
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.desc")
    private String desc;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.created_on")
    private Integer createdOn;

    /**
     * Database Column Remarks:
     *   创建人
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.created_by")
    private String createdBy;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.modified_on")
    private Integer modifiedOn;

    /**
     * Database Column Remarks:
     *   修改人
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.modified_by")
    private String modifiedBy;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.deleted_on")
    private Integer deletedOn;

    /**
     * Database Column Remarks:
     *   状态 0为禁用1为启用
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.state")
    private Byte state;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.content")
    private String content;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source Table: blog_article")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.tag_id")
    public Integer getTagId() {
        return tagId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.tag_id")
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.title")
    public String getTitle() {
        return title;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.title")
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.desc")
    public String getDesc() {
        return desc;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.desc")
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.created_on")
    public Integer getCreatedOn() {
        return createdOn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.created_on")
    public void setCreatedOn(Integer createdOn) {
        this.createdOn = createdOn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.created_by")
    public String getCreatedBy() {
        return createdBy;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.created_by")
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.modified_on")
    public Integer getModifiedOn() {
        return modifiedOn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1247786+08:00", comments="Source field: blog_article.modified_on")
    public void setModifiedOn(Integer modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.modified_by")
    public String getModifiedBy() {
        return modifiedBy;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.modified_by")
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.deleted_on")
    public Integer getDeletedOn() {
        return deletedOn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.deleted_on")
    public void setDeletedOn(Integer deletedOn) {
        this.deletedOn = deletedOn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.state")
    public Byte getState() {
        return state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.state")
    public void setState(Byte state) {
        this.state = state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.content")
    public String getContent() {
        return content;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source field: blog_article.content")
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-04-17T20:22:53.1257759+08:00", comments="Source Table: blog_article")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tagId=").append(tagId);
        sb.append(", title=").append(title);
        sb.append(", desc=").append(desc);
        sb.append(", createdOn=").append(createdOn);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", modifiedOn=").append(modifiedOn);
        sb.append(", modifiedBy=").append(modifiedBy);
        sb.append(", deletedOn=").append(deletedOn);
        sb.append(", state=").append(state);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}