common:
  elasticsearch:
    enabled: true
    auth-username: elastic
    auth-password: hongjun500
    http-ca-file-path: D:\elasticsearch-8.5.3\config\certs\http_ca.crt
    has-using-ssl: true
#    index-name-suffix:

akka:
  actor:
    enabled: true
    actor-system-name: sa




spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 100

# mybatis 配置
mybatis:
  type-aliases-package: com.example.domain.model
  # 自定义类型处理器存放的位置
  type-handlers-package: com.example.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


