common:
  elasticsearch:
    enabled: true
    auth-username: elastic
    auth-password: hongjun500
    http-ca-file-path: J:\elasticsearch-8.5.3\config\certs\http_ca.crt
    has-using-ssl: true
    index-name-prefix:
