spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: hongjun500
  data:
    redis:
      database: 1

common:
  elasticsearch:
    enabled: false
    auth-username: elastic
    auth-password: hongjun500
    http-ca-file-path: J:\elasticsearch-8.5.3\config\certs\http_ca.crt
    has-using-ssl: true
    index-name-suffix: master



# mybatis 配置
mybatis:
  type-aliases-package: com.honjun.model
  # 自定义类型处理器存放的位置
  type-handlers-package: com.honjun.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
