spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: kaggle
      username: mongodb
      password: mongodb
      authentication-database: admin
logging:
  level:
    root: debug
